In [1]:
import pandas as pd
from pathlib import Path
from datetime import datetime

# 2019 Data

In [2]:
# Starting building for a for loop to process, but because of data reporting change in 2020 to 2021, I realized just five 
# separate cleans would be faster for the coding. That is why there is pointless string manipulation for file path.

# Really glad I did this, because the July data I started with didn't look correct for 2023, so all I did to switch
# to June was change the month once. 

prefix = 'citibike-tripdata/20'
year = 190
month = 6
suffix = '-citibike-tripdata.csv'


#Read in the 2019 CSV

data_path = prefix + str(year) + str(month) + suffix

data_path

bike_2019_df = pd.read_csv(
    Path(data_path)
)

bike_2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602,31 Ave & 34 St,40.763154,-73.920827,3570,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054,Greene Ave & Throop Ave,40.689493,-73.942061,3781,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229,Great Jones St,40.727434,-73.993790,326,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771,McKibbin St & Bogart St,40.706237,-73.933871,3016,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441,E 52 St & 2 Ave,40.756014,-73.967416,3159,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125365,232,2019-06-30 23:59:32.8920,2019-07-01 00:03:25.6310,3113,Greenpoint Ave & Manhattan Ave,40.730260,-73.953940,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,25779,Subscriber,1972,1
2125366,477,2019-06-30 23:59:33.6990,2019-07-01 00:07:31.0440,445,E 10 St & Avenue A,40.727408,-73.981420,3737,Stanton St & Norfolk St,40.720747,-73.986274,39522,Subscriber,1981,2
2125367,300,2019-06-30 23:59:47.4050,2019-07-01 00:04:48.1850,3307,West End Ave & W 94 St,40.794165,-73.974124,3320,Central Park West & W 100 St,40.794067,-73.962868,26730,Subscriber,1981,1
2125368,906,2019-06-30 23:59:51.5980,2019-07-01 00:14:58.3210,402,Broadway & E 22 St,40.740343,-73.989551,400,Pitt St & Stanton St,40.719261,-73.981780,38286,Subscriber,1996,1
2125369,1270,2019-06-30 23:59:54.3670,2019-07-01 00:21:05.2750,3788,E 12 St & 4 Av,40.732690,-73.989740,326,E 11 St & 1 Ave,40.729538,-73.984267,38742,Subscriber,1967,1

In [3]:
# Reduce 2.1 million trips down to those only equal to or greater than 15 minutes by subscribers. Result is ~500,000 trips

bike_2019_df = bike_2019_df.loc[(bike_2019_df['tripduration'] >= 900) & (bike_2019_df['usertype'] == 'Subscriber')  & (bike_2019_df['tripduration'] <= 86400)]
bike_2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771,McKibbin St & Bogart St,40.706237,-73.933871,3016,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441,E 52 St & 2 Ave,40.756014,-73.967416,3159,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1
11,1906,2019-06-01 00:00:22.8960,2019-06-01 00:32:09.5860,532,S 5 Pl & S 5 St,40.710451,-73.960876,3712,W 35 St & Dyer Ave,40.754692,-73.997402,16708,Subscriber,1993,1
13,2037,2019-06-01 00:00:30.2570,2019-06-01 00:34:27.7650,3285,W 87 St & Amsterdam Ave,40.788390,-73.974700,540,Lexington Ave & E 29 St,40.743116,-73.982154,27056,Subscriber,1965,2
16,1371,2019-06-01 00:00:33.9910,2019-06-01 00:23:25.3170,223,W 13 St & 7 Ave,40.737815,-73.999947,450,W 49 St & 8 Ave,40.762272,-73.987882,25437,Subscriber,1992,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125356,1686,2019-06-30 23:59:20.6670,2019-07-01 00:27:27.1570,504,1 Ave & E 16 St,40.732219,-73.981656,435,W 21 St & 6 Ave,40.741740,-73.994156,27629,Subscriber,1986,2
2125357,1152,2019-06-30 23:59:20.6820,2019-07-01 00:18:33.2820,3687,E 33 St & 1 Ave,40.743227,-73.974498,238,Bank St & Washington St,40.736197,-74.008592,19804,Subscriber,1971,1
2125358,2530,2019-06-30 23:59:22.7200,2019-07-01 00:41:33.0190,3314,W 95 St & Broadway,40.793770,-73.971888,3328,W 100 St & Manhattan Ave,40.795000,-73.964500,34242,Subscriber,1963,2
2125368,906,2019-06-30 23:59:51.5980,2019-07-01 00:14:58.3210,402,Broadway & E 22 St,40.740343,-73.989551,400,Pitt St & Stanton St,40.719261,-73.981780,38286,Subscriber,1996,1
2125369,1270,2019-06-30 23:59:54.3670,2019-07-01 00:21:05.2750,3788,E 12 St & 4 Av,40.732690,-73.989740,326,E 11 St & 1 Ave,40.729538,-73.984267,38742,Subscriber,1967,1

In [4]:
# Save to a CSV for Tableau

bike_2019_df.to_csv(
        Path('data/2019-data.csv'), index=False
    )

# 2020 Data

In [5]:
# Same ultimately pointless string concat for Path. Keeping in case I do for loop later. 

year = 200
data_path = prefix + str(year) + str(month) + suffix

data_path

bike_2020_df = pd.read_csv(
    Path(data_path)
)

bike_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882268,685,2020-06-30 23:59:41.1160,2020-07-01 00:11:06.7790,503,E 20 St & Park Ave,40.738274,-73.987520,3746,6 Ave & Broome St,40.724308,-74.004730,21056,Customer,1993,2
1882269,446,2020-06-30 23:59:46.4260,2020-07-01 00:07:13.0860,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,30164,Customer,1969,0
1882270,439,2020-06-30 23:59:47.4770,2020-07-01 00:07:06.5590,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,43742,Customer,1986,1
1882271,890,2020-06-30 23:59:53.3950,2020-07-01 00:14:43.4270,3852,Stewart Ave & Johnson Ave,40.708690,-73.925870,3054,Greene Ave & Throop Ave,40.689493,-73.942061,15787,Subscriber,1994,1
1882272,433,2020-06-30 23:59:53.9010,2020-07-01 00:07:07.0950,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,261,Johnson St & Gold St,40.694749,-73.983625,38767,Customer,1990,1

In [6]:
# Filters this time take it from 2.1 million to just shy of 400,000 trips.

bike_2020_df = bike_2020_df.loc[(bike_2020_df['tripduration'] >= 900) & (bike_2020_df['usertype'] == 'Subscriber')  & (bike_2020_df['tripduration'] <= 86400)]
bike_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
9,2714,2020-06-01 00:00:50.3410,2020-06-01 00:46:04.4770,319,Fulton St & Broadway,40.711066,-74.009447,455,1 Ave & E 44 St,40.750020,-73.969053,41760,Subscriber,1989,1
18,1552,2020-06-01 00:01:13.7200,2020-06-01 00:27:06.1410,280,E 10 St & 5 Ave,40.733320,-73.995101,473,Rivington St & Chrystie St,40.721101,-73.991925,43196,Subscriber,1982,1
26,1943,2020-06-01 00:01:53.2620,2020-06-01 00:34:16.3190,250,Lafayette St & Jersey St,40.724561,-73.995653,487,E 20 St & FDR Drive,40.733143,-73.975739,14632,Subscriber,1977,2
28,961,2020-06-01 00:02:07.0130,2020-06-01 00:18:08.9470,3263,Cooper Square & Astor Pl,40.729515,-73.990753,330,Reade St & Broadway,40.714505,-74.005628,28461,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882258,2913,2020-06-30 23:59:19.9590,2020-07-01 00:47:53.8170,426,West St & Chambers St,40.717548,-74.013221,545,E 23 St & 1 Ave,40.736502,-73.978095,39437,Subscriber,1990,1
1882259,1302,2020-06-30 23:59:20.3220,2020-07-01 00:21:03.1120,3537,Carlton Ave & Dean St,40.680974,-73.971010,3179,Park Ave & Marcus Garvey Blvd,40.698617,-73.941342,38446,Subscriber,1988,1
1882261,1652,2020-06-30 23:59:27.1720,2020-07-01 00:26:59.4790,380,W 4 St & 7 Ave S,40.734011,-74.002939,3106,Driggs Ave & N Henry St,40.723250,-73.943080,35994,Subscriber,1980,1
1882264,1386,2020-06-30 23:59:30.4600,2020-07-01 00:22:36.9620,3177,W 84 St & Broadway,40.786795,-73.977112,3141,1 Ave & E 68 St,40.765005,-73.958185,17056,Subscriber,1962,1
1882266,1019,2020-06-30 23:59:35.1490,2020-07-01 00:16:34.2980,3285,W 87 St & Amsterdam Ave,40.788390,-73.974700,4020,Bradhurst Ave & W 148 St,40.825125,-73.941616,33460,Subscriber,1985,1

In [7]:
# Save to CSV

bike_2020_df.to_csv(
        Path('data/2020-data.csv'), index=False
    )

# 2021 Data

In [8]:
# Same import idea with string manipulation.

year = 210
data_path = prefix + str(year) + str(month) + suffix

data_path

bike_2021_df = pd.read_csv(
    Path(data_path)
)

bike_2021_df

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2707176056.py:8: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike_2021_df = pd.read_csv(

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4B923B054861DAEF,docked_bike,2021-06-01 23:12:34,2021-06-01 23:14:46,Driggs Ave & N 9 St,5411.08,Bayard St & Leonard St,5442.05,40.718169,-73.955201,40.719156,-73.948854,member
1,7F5D78629F671C01,docked_bike,2021-06-16 17:14:56,2021-06-16 17:29:15,Fulton St & Broadway,5175.08,Mercer St & Spring St,5532.01,40.711066,-74.009447,40.723627,-73.999496,casual
2,3F11FC94B816A370,docked_bike,2021-06-07 19:41:55,2021-06-07 19:51:28,Devoe St & Lorimer St,5259.06,Manhattan Av & Leonard St,5442.09,40.713352,-73.949103,40.720840,-73.948440,casual
3,9116683DA18320D9,electric_bike,2021-06-17 15:13:15,2021-06-17 15:33:25,Driggs Ave & N 9 St,5411.08,Greenwich Ave & Charles St,5914.08,40.718169,-73.955201,40.735238,-74.000271,member
4,FBBF59A0A03AC3AF,electric_bike,2021-06-18 08:27:03,2021-06-18 08:53:37,Graham Ave & Conselyea St,5291.05,E 30 St & Park Ave S,6206.08,40.715143,-73.944507,40.744449,-73.983035,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3178076,10227FE55F9A9D9D,classic_bike,2021-06-24 19:04:49,2021-06-24 19:29:13,West St & Chambers St,5329.03,Spruce St & Gold St,5137.13,40.717548,-74.013221,40.710323,-74.004323,casual
3178077,256CAF6CF26AD368,docked_bike,2021-06-14 15:18:43,2021-06-14 15:26:39,W 20 St & 8 Ave,6224.05,W 33 St & 7 Ave,6407.07,40.743453,-74.000040,40.750200,-73.990931,member
3178078,F0A4F19ACDE41D6D,docked_bike,2021-06-18 11:22:59,2021-06-18 11:23:57,W 20 St & 8 Ave,6224.05,W 22 St & 8 Ave,6224.03,40.743453,-74.000040,40.744751,-73.999154,member
3178079,3DEAD34FC758DAEF,docked_bike,2021-06-18 11:31:14,2021-06-18 11:32:25,W 20 St & 8 Ave,6224.05,W 22 St & 8 Ave,6224.03,40.743453,-74.000040,40.744751,-73.999154,member
3178080,7DF49539C7E41D56,docked_bike,2021-06-18 11:18:02,2021-06-18 11:19:39,W 20 St & 8 Ave,6224.05,W 22 St & 8 Ave,6224.03,40.743453,-74.000040,40.744751,-73.999154,member

In [9]:
# This time, due to data reporting change, we need to calculate the trip duration ourselves before applying filter.


# These lines change the start and end times to datetime format
bike_2021_df['started_at'] = pd.to_datetime(bike_2021_df['started_at'], format="%Y-%m-%d %H:%M:%S.%f")
bike_2021_df['ended_at'] = pd.to_datetime(bike_2021_df['ended_at'], format="%Y-%m-%d %H:%M:%S.%f")

# This adds another column with the calculated trip duration. 
bike_2021_df['tripduration'] = (bike_2021_df['ended_at'] - bike_2021_df['started_at']).dt.total_seconds().astype('int64')

# And now we apply the same filter as before. Note that 'Subscriber' became 'member' in a renamed column.
bike_2021_df = bike_2021_df.loc[(bike_2021_df['tripduration'] >= 900) & (bike_2021_df['member_casual'] == 'member') & (bike_2021_df['tripduration'] <= 86400)]
bike_2021_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
3,9116683DA18320D9,electric_bike,2021-06-17 15:13:15,2021-06-17 15:33:25,Driggs Ave & N 9 St,5411.08,Greenwich Ave & Charles St,5914.08,40.718169,-73.955201,40.735238,-74.000271,member,1210
4,FBBF59A0A03AC3AF,electric_bike,2021-06-18 08:27:03,2021-06-18 08:53:37,Graham Ave & Conselyea St,5291.05,E 30 St & Park Ave S,6206.08,40.715143,-73.944507,40.744449,-73.983035,member,1594
9,2C12EBAC06239AE4,docked_bike,2021-06-14 20:02:09,2021-06-14 20:28:57,Perry St & Bleecker St,5922.07,Christopher St & Greenwich St,5847.01,40.735353,-74.004830,40.732916,-74.007114,member,1608
11,778DE4F64AD87269,electric_bike,2021-06-27 10:30:51,2021-06-27 10:49:51,Driggs Ave & N 9 St,5411.08,Cumberland St & Lafayette Ave,4428.02,40.718170,-73.955201,40.687534,-73.972652,member,1140
16,0F39768163B40A48,electric_bike,2021-06-11 11:04:44,2021-06-11 11:22:27,FDR Drive & E 35 St,6230.04,E 91 St & Park Ave,7344.05,40.744219,-73.971212,40.783502,-73.955327,member,1063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3178051,EDD8133FC039A411,electric_bike,2021-06-22 21:28:01,2021-06-22 22:00:29,Broadway & W 51 St,6779.04,W 129 St & Convent Ave,7818.17,40.762288,-73.983362,40.814394,-73.953247,member,1948
3178060,AF51F1817BE35D5C,docked_bike,2021-06-01 18:19:14,2021-06-01 18:38:35,10 Ave & W 28 St,6459.04,W 51 St & 6 Ave,6740.1,40.750663,-74.001768,40.760660,-73.980420,member,1161
3178064,62C8443682591404,docked_bike,2021-06-09 23:23:35,2021-06-09 23:46:49,Willoughby Ave & Walworth St,4634.02,Cypress Ave & Palmetto St,4921.04,40.693317,-73.953819,40.701573,-73.908763,member,1394
3178065,888A7F2619909CD1,electric_bike,2021-06-16 22:00:38,2021-06-16 22:27:54,Wythe Ave & Metropolitan Ave,5348.02,W 22 St & 8 Ave,6224.03,40.716887,-73.963198,40.744751,-73.999154,member,1636
3178073,9C89DDE35CF64227,classic_bike,2021-06-26 09:23:41,2021-06-26 09:40:41,W Broadway & W Houston St,5644.05,W 33 St & 7 Ave,6407.07,40.726378,-74.000472,40.750200,-73.990931,member,1020

In [10]:
# Save to CSV

bike_2021_df.to_csv(
        Path('data/2021-data.csv'), index=False
    )

# 2022 Data

In [11]:
# Once again, the import saved for possible later for loop use.

year = 220
data_path = prefix + str(year) + str(month) + suffix

data_path

bike_2022_df = pd.read_csv(
    Path(data_path)
)

bike_2022_df

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3677681949.py:8: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike_2022_df = pd.read_csv(

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FD85DE523427365B,classic_bike,2022-06-08 18:55:00,2022-06-08 18:58:13,E 149 St & Park Ave,7884.04,Morris Ave & E 153 St,7901.04,40.818154,-73.925294,40.820036,-73.921411,member
1,E1DF44B06B360036,classic_bike,2022-06-18 16:34:50,2022-06-18 16:47:49,E 115 St & Madison Ave,7599.02,W 148 St & Amsterdam Ave,8033.09,40.798983,-73.944716,40.827075,-73.945909,member
2,72B6DBF42BC1F9E1,classic_bike,2022-06-11 17:57:00,2022-06-11 18:07:33,E 115 St & Madison Ave,7599.02,2 Ave & E 99 St,7386.10,40.798944,-73.944846,40.786259,-73.945526,member
3,5FABA5CB97A6EA64,classic_bike,2022-06-23 17:32:04,2022-06-23 17:38:36,W Broadway & Spring St,5569.06,N Moore St & Hudson St,5470.02,40.724947,-74.001659,40.719961,-74.008443,member
4,EBA54764AA1A3A41,classic_bike,2022-06-30 16:17:43,2022-06-30 16:27:58,E 14 St & 1 Ave,5779.1,5 Ave & E 29 St,6248.06,40.731393,-73.982867,40.745168,-73.986831,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432878,52758C21D58728B4,classic_bike,2022-06-25 00:45:19,2022-06-25 00:58:01,Norman St & Wyckoff Ave,4654.01,Grove St & Broadway,4526.01,40.695170,-73.903110,40.690470,-73.923511,casual
3432879,2F2B099B77266BF2,classic_bike,2022-06-21 16:52:08,2022-06-21 17:16:43,Railroad Ave & Kay Ave,4990.02,Grove St & Broadway,4526.01,40.705148,-73.970781,40.690470,-73.923511,member
3432880,AEE172A41A2FDA65,classic_bike,2022-06-29 17:58:20,2022-06-29 18:12:10,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432881,3E6A2E15FD49F94E,classic_bike,2022-06-16 19:31:34,2022-06-16 19:42:42,Bushwick Ave & Powers St,5250.05,S 4 St & Wythe Ave,5204.05,40.712477,-73.941000,40.712859,-73.965903,member
3432882,EA18E4BF86FD46F8,classic_bike,2022-06-16 12:15:02,2022-06-16 12:16:40,Broadway & W 51 St,6779.04,8 Ave & W 49 St,6747.07,40.762288,-73.983362,40.761712,-73.986551,member

In [12]:
# Exact same as 2021 recalculation. 

bike_2022_df['started_at'] = pd.to_datetime(bike_2022_df['started_at'], format="%Y-%m-%d %H:%M:%S.%f")
bike_2022_df['ended_at'] = pd.to_datetime(bike_2022_df['ended_at'], format="%Y-%m-%d %H:%M:%S.%f")

bike_2022_df['tripduration'] = (bike_2022_df['ended_at'] - bike_2022_df['started_at']).dt.total_seconds().astype('int64')

bike_2022_df = bike_2022_df.loc[(bike_2022_df['tripduration'] >= 900) & (bike_2022_df['member_casual'] == 'member')  & (bike_2022_df['tripduration'] <= 86400)]
bike_2022_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
8,33576BC1E688B07E,classic_bike,2022-06-09 18:58:27,2022-06-09 19:14:29,E 115 St & Madison Ave,7599.02,E 115 St & Madison Ave,7599.02,40.798944,-73.944846,40.798944,-73.944846,member,962
11,A720895B07CEE30D,electric_bike,2022-06-22 08:31:20,2022-06-22 08:59:54,Fulton St & Adams St,4637.06,Hudson Blvd E & W 36 St,6611.05,40.692418,-73.989495,40.756306,-73.999511,member,1714
13,DB6B93E416D02850,classic_bike,2022-06-18 18:42:32,2022-06-18 19:12:48,1 Pl & Clinton St,4193.14,Park Cir & East Dr,3344.02,40.680959,-73.999057,40.651566,-73.972212,member,1816
19,E67C918BA01E8987,classic_bike,2022-06-25 18:59:45,2022-06-25 19:16:18,1 Pl & Clinton St,4193.14,Caton Ave & E 7 St,3199.01,40.680860,-73.999223,40.647718,-73.973663,member,993
21,FB5C732D3DAFB52C,classic_bike,2022-06-26 20:38:33,2022-06-26 21:20:20,1 Pl & Clinton St,4193.14,Evergreen Ave & Noll St,4873.08,40.680959,-73.999057,40.701060,-73.933180,member,2507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432862,E0289F114DFB3F44,classic_bike,2022-06-06 13:33:08,2022-06-06 13:56:02,Norfolk St & Broome St,5374.01,S 4 St & Wythe Ave,5204.05,40.717227,-73.988021,40.712859,-73.965903,member,1374
3432867,6D022573CBED8F9C,electric_bike,2022-06-17 18:40:37,2022-06-17 19:05:44,Lincoln Pl & Classon Ave,3960.01,S 4 St & Wythe Ave,5204.05,40.672168,-73.960900,40.712859,-73.965903,member,1507
3432873,AD06D2FC859519F0,classic_bike,2022-06-13 11:11:43,2022-06-13 11:43:08,Forsyth St & Canal St,5270.07,8 Ave & W 49 St,6747.07,40.715815,-73.994224,40.761712,-73.986551,member,1885
3432874,AD4D2B6CF3D640DA,classic_bike,2022-06-02 18:48:15,2022-06-02 19:03:22,E 27 St & Park Ave S,6131.13,8 Ave & W 49 St,6747.07,40.742752,-73.984716,40.761712,-73.986551,member,907
3432879,2F2B099B77266BF2,classic_bike,2022-06-21 16:52:08,2022-06-21 17:16:43,Railroad Ave & Kay Ave,4990.02,Grove St & Broadway,4526.01,40.705148,-73.970781,40.690470,-73.923511,member,1475

In [13]:
# Save to CSV

bike_2022_df.to_csv(
        Path('data/2022-data.csv'), index=False
    )

# 2023 Data

In [15]:
# Final year of data read

year = 230
data_path = prefix + str(year) + str(month) + suffix

data_path

bike_2023_df = pd.read_csv(
    Path(data_path)
)

bike_2023_df

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2802345719.py:8: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike_2023_df = pd.read_csv(

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,984F50BCBC76DD9A,classic_bike,2023-06-11 06:54:21,2023-06-11 07:12:28,W 84 St & Columbus Ave,7382.04,Amsterdam Ave & W 125 St,7800.03,40.785000,-73.972834,40.813358,-73.956461,member
1,03E3D62E7FB76B05,classic_bike,2023-06-19 15:23:11,2023-06-19 16:00:05,E 89 St & York Ave,7204.08,Mott St & Prince St,5561.04,40.777958,-73.945928,40.723180,-73.994800,member
2,8E7EE421A0B8BBF3,classic_bike,2023-06-06 16:07:05,2023-06-06 16:15:14,E 51 St & 2 Ave,6575.03,E 25 St & 1 Ave,6004.07,40.755357,-73.967489,40.738177,-73.977387,member
3,24D66A0C46493CB1,classic_bike,2023-06-26 19:52:23,2023-06-26 19:55:47,India St Pier,5794.05,Franklin St & Dupont St,5944.01,40.731735,-73.961239,40.735640,-73.958660,member
4,E944882A074B8F61,classic_bike,2023-06-05 08:57:57,2023-06-05 09:13:36,E 47 St & 2 Ave,6498.1,5 Ave & E 29 St,6248.06,40.753231,-73.970325,40.745168,-73.986831,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3560254,E6B04D2FD398493E,classic_bike,2023-06-22 18:06:15,2023-06-22 18:19:31,University Pl & E 8 St,5755.14,Bialystoker Pl & Delancey St,5335.03,40.731437,-73.994903,40.716226,-73.982612,member
3560255,A9C0665FC912A63B,classic_bike,2023-06-12 09:16:47,2023-06-12 09:42:18,N 7 St & Driggs Ave,5340.01,31 St & Thomson Ave,6227.02,40.716967,-73.956388,40.744697,-73.935404,member
3560256,C6B241D76A0137FD,classic_bike,2023-06-11 17:23:58,2023-06-11 18:02:36,12 Ave & W 125 St,7886.02,Central Park S & 6 Ave,6876.04,40.818299,-73.960405,40.765909,-73.976342,member
3560257,B218070FEA49C6B3,classic_bike,2023-06-27 18:16:21,2023-06-27 18:33:12,W 34 St & 11 Ave,6578.01,11 Ave & W 59 St,7059.01,40.755942,-74.002116,40.771497,-73.990460,casual
3560258,69FB0F587F4022B6,classic_bike,2023-06-02 14:25:05,2023-06-02 14:32:29,Sullivan St & Washington Sq,5721.01,8 Ave & W 16 St,6072.11,40.730477,-73.999061,40.740983,-74.001702,member

In [16]:
# Same as 2021 and 2022 calculations and filters "%Y-%m-%d %H:%M:%S"

bike_2023_df['started_at'] = pd.to_datetime(bike_2023_df['started_at'], format="%Y-%m-%d %H:%M:%S.%f")
bike_2023_df['ended_at'] = pd.to_datetime(bike_2023_df['ended_at'], format="%Y-%m-%d %H:%M:%S.%f")

bike_2023_df['tripduration'] = (bike_2023_df['ended_at'] - bike_2023_df['started_at']).dt.total_seconds().astype('int64')

bike_2023_df = bike_2023_df.loc[(bike_2023_df['tripduration'] >= 900) & (bike_2023_df['member_casual'] == 'member')  & (bike_2023_df['tripduration'] <= 86400)]
bike_2023_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,tripduration
0,984F50BCBC76DD9A,classic_bike,2023-06-11 06:54:21,2023-06-11 07:12:28,W 84 St & Columbus Ave,7382.04,Amsterdam Ave & W 125 St,7800.03,40.785000,-73.972834,40.813358,-73.956461,member,1087
1,03E3D62E7FB76B05,classic_bike,2023-06-19 15:23:11,2023-06-19 16:00:05,E 89 St & York Ave,7204.08,Mott St & Prince St,5561.04,40.777958,-73.945928,40.723180,-73.994800,member,2214
4,E944882A074B8F61,classic_bike,2023-06-05 08:57:57,2023-06-05 09:13:36,E 47 St & 2 Ave,6498.1,5 Ave & E 29 St,6248.06,40.753231,-73.970325,40.745168,-73.986831,member,939
9,21B21C62C315DDA8,classic_bike,2023-06-08 10:50:29,2023-06-08 12:03:56,7 Ave & Park Pl,4125.07,5 St & Market St,4843.01,40.677511,-73.973365,40.699997,-73.974401,member,4407
16,0291AC3D49E8A54B,classic_bike,2023-06-29 18:34:38,2023-06-29 18:55:17,E 56 St & 3 Ave,6691.11,Franklin St & Dupont St,5944.01,40.759188,-73.966985,40.735640,-73.958660,member,1239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3560251,AB5DC3A0A812221F,classic_bike,2023-06-17 06:37:15,2023-06-17 06:56:15,Melrose St & Broadway,4801.04,Broadway & E 21 St,6098.10,40.697455,-73.935870,40.739888,-73.989586,member,1140
3560252,FAC81C236262B930,classic_bike,2023-06-09 18:49:56,2023-06-09 19:06:30,Clinton St & 4 Place,4119.04,5 Ave & 41 St,3306.03,40.678400,-74.000183,40.649983,-74.005144,member,994
3560253,F09A7E2CA1268545,classic_bike,2023-06-15 14:52:57,2023-06-15 15:09:32,W 34 St & 11 Ave,6578.01,Broadway & E 21 St,6098.10,40.755942,-74.002116,40.739888,-73.989586,member,995
3560255,A9C0665FC912A63B,classic_bike,2023-06-12 09:16:47,2023-06-12 09:42:18,N 7 St & Driggs Ave,5340.01,31 St & Thomson Ave,6227.02,40.716967,-73.956388,40.744697,-73.935404,member,1531
3560256,C6B241D76A0137FD,classic_bike,2023-06-11 17:23:58,2023-06-11 18:02:36,12 Ave & W 125 St,7886.02,Central Park S & 6 Ave,6876.04,40.818299,-73.960405,40.765909,-73.976342,member,2318

In [17]:
# Save to CSV

bike_2023_df.to_csv(
        Path('data/2023-data.csv'), index=False
    )

# Attempt to merge all

In [18]:
# Organize all the dataframes to be the same // Code is same for 2019 and 2020, then altered for the group of 2021, 2022 and 2023

bike_2019_df['starttime'] = pd.to_datetime(bike_2019_df['starttime'], format="%Y-%m-%d %H:%M:%S.%f")
bike_2019_df['stoptime'] = pd.to_datetime(bike_2019_df['stoptime'], format="%Y-%m-%d %H:%M:%S.%f")

bike_2019_df.rename(columns={'starttime': 'started_at', 'stoptime': 'ended_at', 'usertype': 'member_casual'}, inplace=True)
bike_2019_df.rename(columns={'start station id': 'start_station_id', 'start station name': 'start_station_name', 'start station latitude': 'start_lat', 'start station longitude': 'start_lng'}, inplace=True)
bike_2019_df.rename(columns={'end station id': 'end_station_id', 'end station name': 'end_station_name', 'end station latitude': 'end_lat', 'end station longitude': 'end_lng'}, inplace=True)
bike_2019_df.drop(columns=['bikeid', 'birth year', 'gender', 'member_casual', 'start_station_id', 'end_station_id'], inplace=True)
bike_2019_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)

bike_2019_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 537091 entries, 3 to 2125369
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       537091 non-null  int64
 1   started_at          537091 non-null  datetime64[ns]
 2   ended_at            537091 non-null  datetime64[ns]
 3   start_station_name  537091 non-null  object
 4   start_lat           537091 non-null  float64
 5   start_lng           537091 non-null  float64
 6   end_station_name    537091 non-null  object
 7   end_lat             537091 non-null  float64
 8   end_lng             537091 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 41.0+ MB

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df['starttime'] = pd.to_datetime(bike_2019_df['starttime'], format="%Y-%m-%d %H:%M:%S.%f")
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df['stoptime'] = pd.to_datetime(bike_2019_df['stoptime'], format="%Y-%m-%d %H:%M:%S.%f")
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.rename(columns={'starttime': 'started_at', 'stoptime': 'ended_at', 'usertype': 'member_casual'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.rename(columns={'start station id': 'start_station_id', 'start station name': 'start_station_name', 'start station latitude': 'start_lat', 'start station longitude': 'start_lng'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.rename(columns={'end station id': 'end_station_id', 'end station name': 'end_station_name', 'end station latitude': 'end_lat', 'end station longitude': 'end_lng'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.drop(columns=['bikeid', 'birth year', 'gender', 'member_casual', 'start_station_id', 'end_station_id'], inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1788339774.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)

In [19]:
# Organize all the dataframes to be the same

bike_2020_df['starttime'] = pd.to_datetime(bike_2020_df['starttime'], format="%Y-%m-%d %H:%M:%S.%f")
bike_2020_df['stoptime'] = pd.to_datetime(bike_2020_df['stoptime'], format="%Y-%m-%d %H:%M:%S.%f")

bike_2020_df.rename(columns={'starttime': 'started_at', 'stoptime': 'ended_at', 'usertype': 'member_casual'}, inplace=True)
bike_2020_df.rename(columns={'start station id': 'start_station_id', 'start station name': 'start_station_name', 'start station latitude': 'start_lat', 'start station longitude': 'start_lng'}, inplace=True)
bike_2020_df.rename(columns={'end station id': 'end_station_id', 'end station name': 'end_station_name', 'end station latitude': 'end_lat', 'end station longitude': 'end_lng'}, inplace=True)
bike_2020_df.drop(columns=['bikeid', 'birth year', 'gender', 'member_casual', 'start_station_id', 'end_station_id'], inplace=True)
bike_2020_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)

bike_2020_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 630853 entries, 1 to 1882266
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       630853 non-null  int64
 1   started_at          630853 non-null  datetime64[ns]
 2   ended_at            630853 non-null  datetime64[ns]
 3   start_station_name  630853 non-null  object
 4   start_lat           630853 non-null  float64
 5   start_lng           630853 non-null  float64
 6   end_station_name    630853 non-null  object
 7   end_lat             630853 non-null  float64
 8   end_lng             630853 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 48.1+ MB

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df['starttime'] = pd.to_datetime(bike_2020_df['starttime'], format="%Y-%m-%d %H:%M:%S.%f")
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df['stoptime'] = pd.to_datetime(bike_2020_df['stoptime'], format="%Y-%m-%d %H:%M:%S.%f")
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.rename(columns={'starttime': 'started_at', 'stoptime': 'ended_at', 'usertype': 'member_casual'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.rename(columns={'start station id': 'start_station_id', 'start station name': 'start_station_name', 'start station latitude': 'start_lat', 'start station longitude': 'start_lng'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.rename(columns={'end station id': 'end_station_id', 'end station name': 'end_station_name', 'end station latitude': 'end_lat', 'end station longitude': 'end_lng'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.drop(columns=['bikeid', 'birth year', 'gender', 'member_casual', 'start_station_id', 'end_station_id'], inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\2029926352.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)

In [20]:
# Organize all the dataframes to be the same

bike_2021_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
bike_2021_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)
bike_2021_df = bike_2021_df[['trip_duration', 'started_at', 'ended_at', 'start_station_name', 'start_lat', 'start_lng', 'end_station_name', 'end_lat', 'end_lng']]
bike_2021_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 696786 entries, 3 to 3178073
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       696786 non-null  int64
 1   started_at          696786 non-null  datetime64[ns]
 2   ended_at            696786 non-null  datetime64[ns]
 3   start_station_name  696779 non-null  object
 4   start_lat           696786 non-null  float64
 5   start_lng           696786 non-null  float64
 6   end_station_name    693168 non-null  object
 7   end_lat             693916 non-null  float64
 8   end_lng             693916 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 53.2+ MB

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\103626308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2021_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\103626308.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2021_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)

In [21]:
# Organize all the dataframes to be the same

bike_2022_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
bike_2022_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)
bike_2022_df = bike_2022_df[['trip_duration', 'started_at', 'ended_at', 'start_station_name', 'start_lat', 'start_lng', 'end_station_name', 'end_lat', 'end_lng']]
bike_2022_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 791222 entries, 8 to 3432879
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       791222 non-null  int64
 1   started_at          791222 non-null  datetime64[ns]
 2   ended_at            791222 non-null  datetime64[ns]
 3   start_station_name  791222 non-null  object
 4   start_lat           791222 non-null  float64
 5   start_lng           791222 non-null  float64
 6   end_station_name    789302 non-null  object
 7   end_lat             791216 non-null  float64
 8   end_lng             791216 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 60.4+ MB

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1219733443.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2022_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\1219733443.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2022_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)

In [22]:
# Organize all the dataframes to be the same

bike_2023_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
bike_2023_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)
bike_2023_df = bike_2023_df[['trip_duration', 'started_at', 'ended_at', 'start_station_name', 'start_lat', 'start_lng', 'end_station_name', 'end_lat', 'end_lng']]
bike_2023_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 734061 entries, 0 to 3560256
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   trip_duration       734061 non-null  int64
 1   started_at          734061 non-null  datetime64[ns]
 2   ended_at            734061 non-null  datetime64[ns]
 3   start_station_name  732927 non-null  object
 4   start_lat           734061 non-null  float64
 5   start_lng           734061 non-null  float64
 6   end_station_name    731007 non-null  object
 7   end_lat             734053 non-null  float64
 8   end_lng             734053 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(2)
memory usage: 56.0+ MB

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3100302966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2023_df.rename(columns={'tripduration': 'trip_duration'}, inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3100302966.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2023_df.drop(columns=['ride_id', 'rideable_type'], inplace=True)

In [23]:
# Drop Nulls

bike_2019_df.dropna(inplace=True)
bike_2020_df.dropna(inplace=True)
bike_2021_df.dropna(inplace=True)
bike_2022_df.dropna(inplace=True)
bike_2023_df.dropna(inplace=True)

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3607608878.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df.dropna(inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3607608878.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df.dropna(inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3607608878.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2021_df.dropna(inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3607608878.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2022_df.dropna(inplace=True)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3607608878.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2023_df.dropna(inplace=True)

In [24]:
# Grouby by current (2023) station names and find mean of lat/long

lats = bike_2023_df.groupby('start_station_name')['start_lat'].mean().to_dict()
longs = bike_2023_df.groupby('start_station_name')['start_lng'].mean().to_dict()

# print(lats)

#Apply those new lat longs across all datasets

bike_2019_df['start_lat'] = bike_2019_df['start_station_name'].map(lats)
bike_2019_df['start_lng'] = bike_2019_df['start_station_name'].map(longs)

bike_2020_df['start_lat'] = bike_2020_df['start_station_name'].map(lats)
bike_2020_df['start_lng'] = bike_2020_df['start_station_name'].map(longs)

bike_2021_df['start_lat'] = bike_2021_df['start_station_name'].map(lats)
bike_2021_df['start_lng'] = bike_2021_df['start_station_name'].map(longs)

bike_2022_df['start_lat'] = bike_2022_df['start_station_name'].map(lats)
bike_2022_df['start_lng'] = bike_2022_df['start_station_name'].map(longs)

bike_2023_df['start_lat'] = bike_2023_df['start_station_name'].map(lats)
bike_2023_df['start_lng'] = bike_2023_df['start_station_name'].map(longs)

C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df['start_lat'] = bike_2019_df['start_station_name'].map(lats)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2019_df['start_lng'] = bike_2019_df['start_station_name'].map(longs)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df['start_lat'] = bike_2020_df['start_station_name'].map(lats)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2020_df['start_lng'] = bike_2020_df['start_station_name'].map(longs)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2021_df['start_lat'] = bike_2021_df['start_station_name'].map(lats)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2021_df['start_lng'] = bike_2021_df['start_station_name'].map(longs)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2022_df['start_lat'] = bike_2022_df['start_station_name'].map(lats)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2022_df['start_lng'] = bike_2022_df['start_station_name'].map(longs)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2023_df['start_lat'] = bike_2023_df['start_station_name'].map(lats)
C:\Users\seana\AppData\Local\Temp\ipykernel_17972\3898274715.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_2023_df['start_lng'] = bike_2023_df['start_station_name'].map(longs)

In [25]:
# Make one giant dataset for all

bike_all_df = pd.concat([bike_2019_df, bike_2020_df, bike_2021_df, bike_2022_df, bike_2023_df])

In [26]:
# DropNAs again, as some no longer existing stations remained.

bike_all_df.dropna(inplace=True)

In [27]:
# Save to CSV

bike_all_df.to_csv(
        Path('data/all-data.csv'), index=False
    )

In [ ]:
# year = 170
# for i in range(7):
    
#     month = 6
#     data_path = prefix + str(year) + str(month) + suffix
    
#     june_df = pd.read_csv(
#         Path(data_path)
#     )
    
#     month = 7
#     data_path = prefix + str(year) + str(month) + suffix
    
#     july_df = pd.read_csv(
#         Path(data_path)
#     )
    
#     year_df = pd.concat([june_df, july_df])
    
#     output_path = 'data/20' + str(year)[0:2] + suffix
    
#     year_df.to_csv(
#         Path(output_path), index=False
#     )
    
#     print(output_path)
    
#     year+=10

In [ ]:

# total_df = pd.read_csv('data/2017-citibike-tripdata.csv')
# year = 2018

# for i in range(3):
#     data_path = 'data/' + str(year) + suffix
    
#     temp_df = pd.read_csv(
#         Path(data_path)
#     )
    
#     total_df = pd.concat([total_df, temp_df])
#     year += 1

In [ ]:
# post_total_df = pd.read_csv('data/2021-citibike-tripdata.csv')
# year = 2022

# for i in range(2):
#     data_path = 'data/' + str(year) + suffix
    
#     temp_df = pd.read_csv(
#         Path(data_path)
#     )
    
#     post_total_df = pd.concat([post_total_df, temp_df])
#     year += 1